#服务端口
server:
  port: 8010

#mysql数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/oumengcloud?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: root
    filters: stat
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:127.0.0.1}
    jedis:
      pool:
        max-active: 300  # 最大可用连接数（默认为8，负数表示无限）
        max-idle: 100 # 最大空闲连接数（默认为8，负数表示无限）
        max-wait: 6000ms  # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        min-idle: 10   # 最小空闲连接数（默认为0，该值只有为正数才有用）
    password: abc123456
    timeout: 2000ms
#配置  openFeign 服务请求响应Ribbon
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
