# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8017
    connection-timeout: 5000
    #context-path: /report
spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    # Freemarker 配置
    freemarker:
      #suffix: .ftl
      suffix: .html
      request-context-attribute: request
      template-loader-path: classpath:/templates/
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true 
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources: # 静态资源的路径
        static-locations: classpath:/statics/,classpath:/templates/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis-config.xml
# APP模块
#logging
# Version
version: v1.0.0


#logback日志记录
logback:
    logDir: D:/log
    appName: oumeng-report
    fileType: log