# Spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/oumengcloud?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: root
    filters: stat
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  main:
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true   #开启从注册中心动态创建路由功能 利用微服务名进行路由
      routes:  # =====================================
        - id: oumeng-auth
          uri: lb://oumeng-auth
          order: 8000
          predicates:
            - Path=/api/auth/**   #断言，路径相匹配的进行路由
          filters:
            - StripPrefix=2
        - id: oumeng-crm
          uri: lb://oumeng-crm
          order: 8001
          predicates:
            - Path=/api/crm/**
            - StripPrefix=2
        - id: oumeng-receiver
          uri: lb://oumeng-receiver
          order: 8002
          predicates:
            - Path=/api/receiver/**
          filters:
            - StripPrefix=2
#Ribbon
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

